spring:
    h2:
        console:
            enabled: true
    datasource:
        url: jdbc:h2:mem:bookstore;DATABASE_TO_UPPER=false
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: create-drop
        defer-datasource-initialization: true
server:
    error:
        include-stacktrace: never
